/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.Jugador.*;

/**
 *
 * @author PAAPCA02LC0805
 */
public class Principal extends javax.swing.JFrame {

    Agregar agregar;
    Eliminar eliminar;
    Listar listar;
    Actualizar actualizar;
    //Login login;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        agregar = new Agregar();
        actualizar = new Actualizar();
        eliminar = new Eliminar();
        listar = new Listar();
        //login = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAgregar = new javax.swing.JMenuItem();
        menuEliminarJugador = new javax.swing.JMenuItem();
        menuActualizarJugador = new javax.swing.JMenuItem();
        menuListarJugador = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAyudaJugador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("Archivo");

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrarSesion);
        jMenu1.add(jSeparator2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jugador");

        menuAgregar.setText("Agregar");
        menuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(menuAgregar);

        menuEliminarJugador.setText("Eliminar");
        menuEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuEliminarJugador);

        menuActualizarJugador.setText("Actualizar");
        menuActualizarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuActualizarJugador);

        menuListarJugador.setText("Listar");
        menuListarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarJugador);
        jMenu2.add(jSeparator1);

        menuAyudaJugador.setText("Ayuda");
        menuAyudaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuAyudaJugador);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAyudaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAyudaJugadorActionPerformed

    private void menuListarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarJugadorActionPerformed
        // TODO add your handling code here:
        listar.setVisible(true);
    }//GEN-LAST:event_menuListarJugadorActionPerformed

    private void menuActualizarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarJugadorActionPerformed
        // TODO add your handling code here:
        actualizar.setVisible(true);
    }//GEN-LAST:event_menuActualizarJugadorActionPerformed

    private void menuEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarJugadorActionPerformed
        // TODO add your handling code here:
        eliminar.setVisible(true);
    }//GEN-LAST:event_menuEliminarJugadorActionPerformed

    private void menuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarActionPerformed
        // TODO add your handling code here:
        agregar.setVisible(true);
    }//GEN-LAST:event_menuAgregarActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
      // TODO add your handling code here:
      //login.setVisible(true);
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuActualizarJugador;
    private javax.swing.JMenuItem menuAgregar;
    private javax.swing.JMenuItem menuAyudaJugador;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuEliminarJugador;
    private javax.swing.JMenuItem menuListarJugador;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
