/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import vistas.Jugador.*;

/**
 *
 * @author PAAPCA02LC0800
 */
public class Principal extends javax.swing.JFrame {

    //Login login;
    Agregar agregar;
    Actualizar actualizar;
    Eliminar eliminar;
    Listar listar;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //login = new Login();
        agregar = new Agregar();
        actualizar = new Actualizar();
        eliminar = new Eliminar();
        listar = new Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAyudaJugador = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuAgregarJugador = new javax.swing.JMenuItem();
        menuActualizarJugador = new javax.swing.JMenuItem();
        menuEliminarJugador = new javax.swing.JMenuItem();
        menuListarJugadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        jMenu2.setText("Jugadores");

        menuAyudaJugador.setText("Ayuda");
        jMenu2.add(menuAyudaJugador);
        jMenu2.add(jSeparator1);

        menuAgregarJugador.setText("Agregar");
        menuAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuAgregarJugador);

        menuActualizarJugador.setText("Actualizar");
        menuActualizarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuActualizarJugador);

        menuEliminarJugador.setText("Eliminar");
        menuEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarJugadorActionPerformed(evt);
            }
        });
        jMenu2.add(menuEliminarJugador);

        menuListarJugadores.setText("Listar");
        menuListarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarJugadoresActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarJugadores);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed

        //login.setVisible(true);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarJugadorActionPerformed
        agregar.setVisible(true);
    }//GEN-LAST:event_menuAgregarJugadorActionPerformed

    private void menuActualizarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarJugadorActionPerformed
       actualizar.setVisible(true);
    }//GEN-LAST:event_menuActualizarJugadorActionPerformed

    private void menuEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarJugadorActionPerformed
        eliminar.setVisible(true);
    }//GEN-LAST:event_menuEliminarJugadorActionPerformed

    private void menuListarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarJugadoresActionPerformed
        listar.setVisible(true);
    }//GEN-LAST:event_menuListarJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem menuActualizarJugador;
    private javax.swing.JMenuItem menuAgregarJugador;
    private javax.swing.JMenuItem menuAyudaJugador;
    private javax.swing.JMenuItem menuEliminarJugador;
    private javax.swing.JMenuItem menuListarJugadores;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
